### ISSUE TITLE
Trigger all button

### ISSUE THREAD

**Issue by garthpaine** [ircam-ismm/playground#17]
Any chance we could make the Trigger All button higher?  It is hard to hit accurately when there is a lot going on. Could that be in the config too?

**Comment by b-ma** [comment]
I'm not sure what mean here, would you like something like that?

<img width="1189" alt="Screenshot 2021-11-15 at 17 59 26" src="https://user-images.githubusercontent.com/1013757/141824008-b71e8b8f-25b6-4ab5-af35-52799256f20f.png">

I wouldn't go for the config idea there because I'm afraid we end-up with tens or hundreds of small variables like that, as long as we can I'd prefer we improve the interfaces according to your usage (since you are our _virtuoso_ here :).

**Comment by garthpaine** [comment]
![FCBC04AB-CA3E-4E7A-91A2-F31BEE4863E9](https://user-images.githubusercontent.com/3523978/141834131-58425f3b-52a8-42f4-8af2-71fffd5ffdbb.png)

yes that would help. I need to trigger things fast with the orchestra and I am some times missing the smaller button when I am also doing things on the other interfaces at the same time.

**Comment by b-ma** [comment]
ok I'll do that that tomorrow
